# Generated by Django 3.1.4 on 2021-01-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resourcelinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=50)),
            ],
        ),
    ]
