# Generated by Django 3.1.4 on 2021-01-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcelinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelinks',
            name='link',
            field=models.TextField(default='link'),
            preserve_default=False,
        ),
    ]
